name: Populate Depot JSON

on:
  # runs when this repository's releases are modified
  release:
  # allows for manual dispatching of the workflow
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions:
      # permits reading of releases and writing to the depot branch
      contents: write
    steps:
      - name: Generate PROS depot
        uses: jerrylum/pros-depot@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}